Repository openshift/scapresults, pull requests merged in 2019-12, with the labels that each got.

#3 Make calls to kubernetes more resilient
  Makefile
  cmd/scapresults/main.go
  go.mod
  go.sum
Labels: lgtm, size/M

#4 Ignore GoLand directory
  .gitignore
Labels: size/XS

#6 Correct my github handle
  OWNERS
Labels: lgtm, size/XS
